=== effanville/PortfolioDatabase/.nuke/build.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Build Schema",
  "$ref": "#/definitions/build",
  "definitions": {
    "build": {
      "type": "object",
      "properties": {
        "Configuration": {
          "type": "string",
          "description": "Configuration to build - Default is 'Debug'",
          "enum": [
            "Debug",
            "Release"
          ]
        },
        "Continue": {
          "type": "boolean",
          "description": "Indicates to continue a previously failed build attempt"
        },
        "ExecutablePublishProjects": {
          "type": "array",
          "description": "The projects to build as executables",
          "items": {
            "type": "string"
          }
        },
        "Framework": {
          "type": "string",
          "description": "Framework to build with - Current is net7.0"
        },
        "Help": {
          "type": "boolean",
          "description": "Shows the help text for this build assembly"
        },
        "Host": {
          "type": "string",
          "description": "Host for execution. Default is 'automatic'",
          "enum": [
            "AppVeyor",
            "AzurePipelines",
            "Bamboo",
            "Bitbucket",
            "Bitrise",
            "GitHubActions",
            "GitLab",
            "Jenkins",
            "Rider",
            "SpaceAutomation",
            "TeamCity",
            "Terminal",
            "TravisCI",
            "VisualStudio",
            "VSCode"
          ]
        },
        "IsProd": {
          "type": "boolean",
          "description": "Is this a production release"
        },
        "NoLogo": {
          "type": "boolean",
          "description": "Disables displaying the NUKE logo"
        },
        "NugetPackageProjects": {
          "type": "array",
          "description": "The projects to build as nuget packages",
          "items": {
            "type": "string"
          }
        },
        "Partition": {
          "type": "string",
          "description": "Partition to use on CI"
        },
        "Plan": {
          "type": "boolean",
          "description": "Shows the execution plan (HTML)"
        },
        "Profile": {
          "type": "array",
          "description": "Defines the profiles to load",
          "items": {
            "type": "string"
          }
        },
        "PushTag": {
          "type": "boolean",
          "description": "Should this tag be pushed to the remote"
        },
        "Root": {
          "type": "string",
          "description": "Root directory during build execution"
        },
        "Runtime": {
          "type": "string"
        },
        "Skip": {
          "type": "array",
          "description": "List of targets to be skipped. Empty list skips all dependencies",
          "items": {
            "type": "string",
            "enum": [
              "Clean",
              "Compile",
              "DiagnosticPrint",
              "GitTag",
              "Publish",
              "PublishExe",
              "PublishNuget",
              "Release",
              "ReleaseNotes",
              "Test",
              "UpdateVersion"
            ]
          }
        },
        "Solution": {
          "type": "string",
          "description": "Path to a solution file that is automatically loaded"
        },
        "TagRepo": {
          "type": "boolean",
          "description": "Should this version be tagged"
        },
        "Target": {
          "type": "array",
          "description": "List of targets to be invoked. Default is '{default_target}'",
          "items": {
            "type": "string",
            "enum": [
              "Clean",
              "Compile",
              "DiagnosticPrint",
              "GitTag",
              "Publish",
              "PublishExe",
              "PublishNuget",
              "Release",
              "ReleaseNotes",
              "Test",
              "UpdateVersion"
            ]
          }
        },
        "TestProjects": {
          "type": "array",
          "description": "Projects to run unit tests for",
          "items": {
            "type": "string"
          }
        },
        "Verbosity": {
          "type": "string",
          "description": "Logging verbosity during build execution. Default is 'Normal'",
          "enum": [
            "Minimal",
            "Normal",
            "Quiet",
            "Verbose"
          ]
        }
      }
    }
  }
}

=== effanville/PortfolioDatabase/.nuke/parameters.release.json
{
  "$schema": "./build.schema.json",
  "Solution": "FinancePortfolioDatabase.sln",
  "ExecutablePublishProjects": [
    "FPD.UI",
    "FPD.Console"
  ],
  "NugetPackageProjects": [
  ],
  "Configuration": "Release",
  "Framework": "net7.0-windows",
  "Runtime": "win-x64",
  "IsProd": true,
  "TagRepo": true,
  "PushTag": true,
  "TestProjects": [
    "Common.Structure.Tests",
    "Common.Console.Tests",
    "Common.UI.Tests",
    "Common.UI.Wpf.Tests",
    "FinancialStructures.Tests",
    "FPD.Logic.Tests",
    "FPD.Console.Tests"
  ]
}

=== effanville/PortfolioDatabase/.nuke/parameters.json
{
  "$schema": "./build.schema.json",
  "Solution": "FinancePortfolioDatabase.sln",
  "ExecutablePublishProjects": [
    "FPD.UI",
    "FPD.Console"
  ],
  "NugetPackageProjects": [
    "FinancialStructures"
  ],
  "Configuration": "Release",
  "Framework": "net7.0-windows",
  "Runtime": "win-x64",
  "TagRepo": true,
  "PushTag": false,
  "TestProjects": [
    "FinancialStructures.Tests",
    "FPD.Logic.Tests"
  ]
}
